apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: gitops-test-folder
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  resyncPeriod: 0s
  title: GitOps Test Folder
  uid: gitopstestfolder
