apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: grafanacloud
  namespace: grafana
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  resyncPeriod: 0s
  title: GrafanaCloud
  uid: afq0ilsj22n7ka
