apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaNotificationPolicy
metadata:
  name: default-notification-policy
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  resyncPeriod: 0s
  route:
    receiver: grafana-default-email
    group_by:
      - grafana_folder
      - alertname
