apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: grafanacloud-k6
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  resyncPeriod: 0s
  uid: grafanacloud-k6
  datasource:
    name: grafanacloud-k6
    type: k6-datasource
    url: proxy
    access: proxy
    uid: grafanacloud-k6
    isDefault: false
    basicAuth: false
  valuesFrom: null
