apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: synthetic-monitoring
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      app: grafana
  resyncPeriod: 0s
  uid: afcsq9koh5clcd
  datasource:
    name: Synthetic Monitoring
    type: synthetic-monitoring-datasource
    url: ""
    access: proxy
    uid: afcsq9koh5clcd
    isDefault: false
    basicAuth: false
  valuesFrom: null
