apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: extsvc-grafana-incident-datasource
  namespace: grafana
spec:
  instanceName: grafana
  name: extsvc-grafana-incident-datasource
  role: Viewer
  isDisabled: false
