apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: extsvc-k6-app
  namespace: grafana
spec:
  instanceName: grafana
  name: extsvc-k6-app
  role: Viewer
  isDisabled: false
