apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: grafana-mcp
  namespace: grafana
spec:
  instanceName: grafana
  name: grafana-mcp
  role: Admin
  isDisabled: false
