apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-credentials
  namespace: grafana
  annotations:
    grafana-operator/for: Grafana/grafana-cloud-instance
    grafana-operator/secret-kind: Grafana
stringData:
  token: CHANGE_ME
