apiVersion: v1
kind: Secret
metadata:
  name: pagerduty-pagerduty-credentials
  namespace: grafana
  annotations:
    grafana-operator/for: GrafanaContactPoint/PagerDuty
    grafana-operator/secret-kind: GrafanaContactPoint
stringData:
  integrationKey: CHANGE_ME
